---
root: true                      # project-level eslintrc
parser: babel-eslint            # default: esprima

extends:
  # https://www.npmjs.com/package/eslint-config-airbnb-base
  - airbnb
  # https://github.com/prettier/eslint-config-prettier
  - prettier
  - prettier/react

plugins:
  # - react
  # - import
  # https://github.com/prettier/eslint-plugin-prettier
  - prettier

# settings:
#   flowtype:
#     # with this option you do not have to add @flow in files
#     onlyFilesWithFlowAnnotation: false

env:
  es6: true
  browser: true
  commonjs: true
  node: true
  # jasmine: true
  # jest: true
  # jest/globals: true

# globals:
#   fetch: true
#   navigator: true
#   __DEV__: true
#   XMLHttpRequest: true
#   React$Element: true
#   Generator: true

parserOptions:
  ecmaVersion: 2015
  # sourceType: module
  # ecmaFeatures:
  #   jsx: true

# airbnb config overrides
rules:
  prettier/prettier:
    - error
    -
      trailingComma: all
      singleQuote: true
      printWidth: 120
      semi: true
  func-names: [warn, as-needed]
  no-console: off
  no-shadow: off
  consistent-return: off
  no-const-assign: warn
  no-this-before-super: warn
  no-undef: warn
  no-unreachable: warn
  no-unused-vars: warn
  constructor-super: warn
  valid-typeof: warn
